# Generated by Django 4.2.1 on 2023-05-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Termek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azonosito', models.CharField(max_length=20, unique=True)),
                ('nev', models.CharField(max_length=50)),
                ('leiras', models.TextField()),
                ('ar', models.DecimalField(decimal_places=2, max_digits=6)),
                ('raktaron', models.BooleanField(default=False)),
                ('letrehozva', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
